include(${CMAKE_SOURCE_DIR}/cmake/colorPrint.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/InstallModule.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/InstallDirectory.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/InstallPackage.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/InstallFiles.cmake)
include(${CMAKE_SOURCE_DIR}/cmake/findPackage.cmake)
